//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymApp.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GymDBEntities : DbContext
    {
        public GymDBEntities()
            : base("name=GymDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLANTRENORLER> TBLANTRENORLER { get; set; }
        public virtual DbSet<TBLBEDENBILGILERI> TBLBEDENBILGILERI { get; set; }
        public virtual DbSet<TBLGRUPDERSLER> TBLGRUPDERSLER { get; set; }
        public virtual DbSet<TBLOZELDERSLER> TBLOZELDERSLER { get; set; }
        public virtual DbSet<TBLUYEGRUPDERSLERI> TBLUYEGRUPDERSLERI { get; set; }
        public virtual DbSet<TBLUYELER> TBLUYELER { get; set; }
        public virtual DbSet<TBLUYELIKTIPI> TBLUYELIKTIPI { get; set; }
    }
}
