//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymApp.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLGRUPDERSLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLGRUPDERSLER()
        {
            this.TBLUYEGRUPDERSLERI = new HashSet<TBLUYEGRUPDERSLERI>();
        }
    
        public int grupders_id { get; set; }
        public string grupders_ad { get; set; }
        public System.DateTime grupders_tarih { get; set; }
        public System.TimeSpan grupders_saat { get; set; }
        public int grupders_antrenorID { get; set; }
        public int grupders_kapasite { get; set; }
        public string grupders_aktif { get; set; }
        public int grupders_mevcut { get; set; }
    
        public virtual TBLANTRENORLER TBLANTRENORLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLUYEGRUPDERSLERI> TBLUYEGRUPDERSLERI { get; set; }
    }
}
