//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymApp.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLOZELDERSLER
    {
        public int ozelders_id { get; set; }
        public System.DateTime ozelders_tarih { get; set; }
        public System.TimeSpan ozelders_saat { get; set; }
        public int ozelders_antrenorID { get; set; }
        public string ozelders_aktif { get; set; }
        public int ozelders_uyeID { get; set; }
    
        public virtual TBLANTRENORLER TBLANTRENORLER { get; set; }
        public virtual TBLUYELER TBLUYELER { get; set; }
        public virtual TBLUYELER TBLUYELER1 { get; set; }
    }
}
