//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymApp.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLUYELER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLUYELER()
        {
            this.TBLBEDENBILGILERI = new HashSet<TBLBEDENBILGILERI>();
            this.TBLUYEGRUPDERSLERI = new HashSet<TBLUYEGRUPDERSLERI>();
            this.TBLOZELDERSLER = new HashSet<TBLOZELDERSLER>();
            this.TBLOZELDERSLER1 = new HashSet<TBLOZELDERSLER>();
        }
    
        public int uye_id { get; set; }
        public string uye_ad { get; set; }
        public string uye_soyad { get; set; }
        public string uye_telefon { get; set; }
        public string uye_email { get; set; }
        public System.DateTime uye_dogumTarihi { get; set; }
        public System.DateTime uye_kayitTarihi { get; set; }
        public System.DateTime uye_bitisTarihi { get; set; }
        public string uye_aktif { get; set; }
        public string uye_adres { get; set; }
        public string uye_salonda { get; set; }
        public string uye_foto { get; set; }
        public int uye_uyelikTipi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBEDENBILGILERI> TBLBEDENBILGILERI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLUYEGRUPDERSLERI> TBLUYEGRUPDERSLERI { get; set; }
        public virtual TBLUYELIKTIPI TBLUYELIKTIPI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLOZELDERSLER> TBLOZELDERSLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLOZELDERSLER> TBLOZELDERSLER1 { get; set; }
    }
}
