//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymApp.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLUYEGRUPDERSLERI
    {
        public int uyegrupdersler_id { get; set; }
        public int uyegrupdersler_uyeID { get; set; }
        public int uyegrupdersler_grupdersID { get; set; }
    
        public virtual TBLGRUPDERSLER TBLGRUPDERSLER { get; set; }
        public virtual TBLUYELER TBLUYELER { get; set; }
    }
}
